# Generated by Django 2.0.5 on 2018-07-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.CharField(max_length=350)),
                ('truncated', models.CharField(max_length=300)),
                ('fav_count', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=50)),
                ('retweets', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('lang', models.CharField(max_length=10)),
                ('retweeted', models.BooleanField(verbose_name='retweeted')),
                ('hashtags', models.CharField(max_length=200)),
            ],
        ),
    ]
