# Generated by Django 2.0.5 on 2018-07-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_tweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='source',
            field=models.CharField(max_length=200),
        ),
    ]
